# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://github.com/pre-commit/pre-commit-hooks for more hooks by pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Jupyter Notebook clear cells
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.6
    hooks:
      # Run the linter.
      - id: ruff
        name: "ruff isort"
        args: ["--select", "I", "--fix"]
      - id: ruff
        name: "ruff lint"
        args: ["--fix"]
      # Run the formatter.
      - id: ruff-format
        name: "ruff format"
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0
  #   hooks:
  #     - id: mypy
  #       args: [--strict, --explicit-package-bases, --ignore-missing-imports]
